import { DataTypes } from 'sequelize';
import db from '../config/db.js'

const Study = db.define('studies',{
    code:{
        type:DataTypes.STRING,
        allowNull:false
    },
    name:{
        type:DataTypes.STRING,
        allowNull:false
    },
    surveyID:{
        type:DataTypes.STRING,
        allowNull:false
    },
    RegionVarName:{
        type:DataTypes.STRING,
        allowNull:false
    },
    ComunaVarName:{
        type:DataTypes.STRING,
        allowNull:false
    },
    UMPVarName:{
        type:DataTypes.STRING,
        allowNull:false
    },
    expectedCase:{
        type:DataTypes.INTEGER,
        allowNull:false
    },
    startDate:{
        type:DataTypes.DATE        
    },
    status:{
        type:DataTypes.BOOLEAN,
        allowNull:false
    },
    reg1ExpectedCase:{
        type:DataTypes.INTEGER,
        allowNull:false
    },
    reg2ExpectedCase:{
        type:DataTypes.INTEGER,
        allowNull:false
    },
    reg3ExpectedCase:{
        type:DataTypes.INTEGER,
        allowNull:false
    },
    reg4ExpectedCase:{
        type:DataTypes.INTEGER,
        allowNull:false
    },
    reg5ExpectedCase:{
        type:DataTypes.INTEGER,
        allowNull:false
    },
    reg6ExpectedCase:{
        type:DataTypes.INTEGER,
        allowNull:false
    },
    reg7ExpectedCase:{
        type:DataTypes.INTEGER,
        allowNull:false
    },
    reg8ExpectedCase:{
        type:DataTypes.INTEGER,
        allowNull:false
    },
    reg9ExpectedCase:{
        type:DataTypes.INTEGER,
        allowNull:false
    },
    reg10ExpectedCase:{
        type:DataTypes.INTEGER,
        allowNull:false
    },
    reg11ExpectedCase:{
        type:DataTypes.INTEGER,
        allowNull:false
    },
    reg12ExpectedCase:{
        type:DataTypes.INTEGER,
        allowNull:false
    },
    reg13ExpectedCase:{
        type:DataTypes.INTEGER,
        allowNull:false
    },
    reg14ExpectedCase:{
        type:DataTypes.INTEGER,
        allowNull:false
    },
    reg15ExpectedCase:{
        type:DataTypes.INTEGER,
        allowNull:false
    },
    reg16ExpectedCase:{
        type:DataTypes.INTEGER,
        allowNull:false
    },

})

export default Study